version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.6

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - package-lock.json

  lint:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run ESLint
          command: npm run lint

  unit-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - browser-tools/install-chrome
      - run:
          name: Run Unit Tests with Coverage
          command: npm run test:unit
          environment:
            CHROME_BIN: /usr/bin/google-chrome
      - run:
          name: Upload Coverage to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f ./coverage/cep-compass/lcov.info
      - store_artifacts:
          path: coverage
          destination: coverage-reports
      - store_test_results:
          path: coverage

  e2e-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Firebase Tools
          command: npm install -g firebase-tools
      - run:
          name: Enable Firebase Web Frameworks
          command: npx firebase experiments:enable webframeworks
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Start Firebase Emulators
          command: |
            firebase emulators:start --only hosting --project demo-test-project &
            for i in {1..30}; do
              curl -s http://localhost:5001/ && break
              echo "Waiting for Firebase emulators to be ready..."
              sleep 1
            done
            if ! curl -s http://localhost:5001/; then
              echo "Firebase emulators failed to start within the timeout period."
              exit 1
            fi
          background: true
      - run:
          name: Run E2E Tests
          command: npm run test:e2e
          environment:
            FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
            FIREBASE_FUNCTIONS_EMULATOR_HOST: localhost:5001
            HEADLESS_BROWSER: true
            CI: true
      - store_artifacts:
          path: playwright-report
          destination: playwright-reports
      - store_test_results:
          path: playwright-report

  build-check:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Production
          command: npm run build
      - run:
          name: Check Build Size
          command: |
            echo "Build size report:"
            du -sh dist/
            echo "Detailed breakdown:"
            du -h dist/* | sort -hr
      - store_artifacts:
          path: dist
          destination: build-artifacts

workflows:
  test-and-build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - e2e-tests:
          requires:
            - install-dependencies
      - build-check:
          requires:
            - install-dependencies
