version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.6

executors:
  node-executor:
    docker:
      - image: cimg/node:20.19-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - package-lock.json

  lint:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run ESLint
          command: npm run lint

  unit-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - browser-tools/install-chrome
      - run:
          name: Create test results directory
          command: mkdir -p test-results
      - run:
          name: Run Unit Tests with Coverage
          command: npm run test:unit || true
          environment:
            CHROME_BIN: /usr/bin/google-chrome
      - run:
          name: Upload Coverage to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f ./coverage/cep-compass/lcov.info
          when: always
      - store_artifacts:
          path: coverage
          destination: coverage-reports
      - store_test_results:
          path: test-results

  e2e-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - browser-tools/install-chrome
      - run:
          name: Create test results directory
          command: mkdir -p test-results
      - run:
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run:
          name: Enable Firebase Web Frameworks
          command: npx firebase experiments:enable webframeworks
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Run E2E Tests
          command: npx playwright test --config=playwright.config.test.ts || true
          environment:
            HEADLESS_BROWSER: true
            CI: true
      - store_artifacts:
          path: playwright-report
          destination: playwright-reports
      - store_test_results:
          path: test-results

  build-check:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Production
          command: npm run build
      - run:
          name: Check Build Size
          command: |
            echo "Build size report:"
            du -sh dist/
            echo "Detailed breakdown:"
            du -h dist/* | sort -hr
      - store_artifacts:
          path: dist
          destination: build-artifacts

workflows:
  test-and-build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - e2e-tests:
          requires:
            - install-dependencies
      - build-check:
          requires:
            - install-dependencies
